### ISSUE TITLE
"element not interactable" exception in webUI tests

### ISSUE THREAD

**Issue by phil-davis** [owncloud/password_policy#209]
See comment https://github.com/owncloud/password_policy/pull/208#issuecomment-469531140

Intermittently, but "quite a lot" we are getting exceptions in webUI test runs like:
```
exception 'Exception' with message 'element not interactable
          (Session info: chrome=72.0.3626.119)
          (Driver info: chromedriver=2.46.628388 (4a34a70827ac54148e092aafb70504c4ea7ae926),platform=Linux 4.4.0-142-generic x86_64)' in /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:144
        Stack trace:
#0 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(157): WebDriver\Exception::factory(60, 'element not int...')
#1 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/AbstractWebDriver.php(219): WebDriver\AbstractWebDriver->curl('POST', '/value', Array)
#2 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/instaclick/php-webdriver/lib/WebDriver/Container.php(224): WebDriver\AbstractWebDriver->__call('postValue', Array)
#3 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(678): WebDriver\Container->__call('postValue', Array)
#4 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/behat/mink-selenium2-driver/src/Selenium2Driver.php(678): WebDriver\Element->postValue(Array)
#5 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/behat/mink/src/Element/NodeElement.php(105): Behat\Mink\Driver\Selenium2Driver->setValue('(//html/.//*\n[s...', 'guiusr1@ownclou...')
#6 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/behat/mink/src/Element/TraversableElement.php(160): Behat\Mink\Element\NodeElement->setValue('guiusr1@ownclou...')
#7 /var/www/owncloud/tests/acceptance/features/lib/UsersPage.php(385): Behat\Mink\Element\TraversableElement->fillField('newemail', 'guiusr1@ownclou...')
#8 /tmp/ProxyManagerGeneratedProxy__PM__PageUsersPageGeneratedd0256f2e1d2b70cc821d593ed9bd12e9.php(124): Page\UsersPage->createUser(Object(Behat\Mink\Session), 'user1', NULL, 'guiusr1@ownclou...', NULL)
#9 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIUsersContext.php(137): ProxyManagerGeneratedProxy\__PM__\Page\UsersPage\Generatedd0256f2e1d2b70cc821d593ed9bd12e9->createUser(Object(Behat\Mink\Session), 'user1', NULL, 'guiusr1@ownclou...', NULL)
#10 /var/www/owncloud/tests/acceptance/features/bootstrap/WebUIUsersContext.php(166): WebUIUsersContext->theAdminCreatesAUserUsingTheWebUI('creates', 'user1', NULL, 'guiusr1@ownclou...', NULL)
#11 [internal function]: WebUIUsersContext->theAdminCreatesAUserUsingWithoutAPasswordTheWebUI('creates', 'user1', 'guiusr1@ownclou...', NULL)
#12 /var/www/owncloud/apps/password_policy/vendor-bin/behat/vendor/behat/behat/src/Behat/Testwork/Call/Handler/RuntimeCallHandler.php(109): call_user_func_array(Array, Array)
```

Maybe there is some timing issue?
Maybe we get some DOM element early which exists, but then some JS/Ajax... happens and that DOM element is now out-of-date, or is obscured on the webUI by some other element, or has been set to "hidden" or...

**Comment by phil-davis** [comment]
@PVince81 I added this to the next sprint, because it is happening quite a lot.

**Comment by skshetry** [comment]
Is this still happening? Close this? @phil-davis

**Comment by phil-davis** [comment]
CI has been passing each night in the last weeks, so I  guess this problem was fixed.
